<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EducationalContentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('educational_contents')->insert([
            [
                'title' => 'Kenali Anemia',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Edukasi mengenai anemia, gejala umum, dan pentingnya deteksi serta pencegahan sejak dini.',
                'content' => 'Anemia adalah kondisi di mana tubuh kekurangan sel darah merah atau kadar hemoglobin yang cukup untuk mengangkut oksigen ke seluruh tubuh. Hal ini menyebabkan berbagai gangguan kesehatan seperti kelelahan, wajah pucat, dan pusing. Remaja putri berisiko tinggi mengalami anemia karena kebutuhan zat besi yang meningkat selama masa pertumbuhan dan menstruasi. Penting untuk mengenali tanda-tanda anemia sejak dini agar dapat ditangani dengan cepat dan tepat melalui pola makan seimbang, suplementasi zat besi, dan pemeriksaan kesehatan berkala.',
                'url' => '/storage/posters/Kenali-Anemia.png',
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gejala Anemia',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Informasi seputar gejala umum anemia yang sering tidak disadari dan berisiko memburuk.',
                'content' => 'Gejala anemia bisa berbeda pada setiap orang, namun umumnya mencakup wajah pucat, tubuh lemah, sering merasa lelah meskipun tidak beraktivitas berat, pusing, mata berkunang-kunang, dan detak jantung yang cepat. Gejala ini sering kali dianggap sepele, padahal jika dibiarkan bisa memperburuk kondisi kesehatan. Remaja putri perlu memahami bahwa gejala tersebut merupakan sinyal tubuh untuk segera memeriksakan diri dan memperoleh asupan zat besi yang cukup, baik dari makanan maupun suplemen.',
                'url' => '/storage/posters/Gejala-Anemia.png',
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dampak Anemia',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Penjelasan dampak anemia jangka pendek dan panjang terhadap kesehatan dan produktivitas.',
                'content' => 'Dampak jangka pendek anemia pada remaja putri meliputi penurunan konsentrasi belajar, produktivitas, dan imunitas tubuh. Hal ini membuat mereka sulit mengikuti pelajaran, mudah tertular penyakit, dan cepat merasa lelah. Jika tidak ditangani sejak remaja, anemia dapat menimbulkan dampak jangka panjang seperti gangguan pertumbuhan, stunting, dan risiko komplikasi serius saat kehamilan dan persalinan. Oleh karena itu, penting untuk mencegah dan mengobati anemia sejak usia dini agar tidak menimbulkan konsekuensi berkelanjutan.',
                'url' => '/storage/posters/Dampak-Anemia.png',
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cara Agar Tablet Anemia Efektif',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Panduan konsumsi tablet tambah darah agar penyerapan zat besi lebih maksimal.',
                'content' => 'Agar tablet tambah darah bekerja secara optimal, minumlah satu tablet setiap minggu selama setahun penuh. Konsumsi tablet setelah makan malam untuk menghindari rasa mual. Hindari mengonsumsi teh, kopi, atau susu bersamaan karena dapat menghambat penyerapan zat besi. Sebaiknya konsumsi bersama makanan atau minuman yang kaya vitamin C seperti jeruk atau jambu untuk meningkatkan penyerapan. Disiplin dalam mengonsumsi tablet sangat penting agar tubuh mendapatkan manfaat maksimal dan terhindar dari anemia.',
                'url' => '/storage/posters/Cara-Agar-Tablet-Anemia-Efektif.png',
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cegah Anemia',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Langkah-langkah praktis mencegah anemia sejak usia remaja melalui pola hidup sehat.',
                'content' => 'Pencegahan anemia dapat dilakukan dengan cara sederhana namun konsisten. Mulailah dengan pola makan bergizi, mengonsumsi makanan kaya zat besi seperti hati, daging merah, bayam, dan kacang-kacangan. Rutin minum tablet tambah darah setiap minggu, terutama bagi remaja putri yang sedang mengalami masa menstruasi. Gaya hidup sehat, seperti cukup tidur, olahraga, dan tidak melewatkan sarapan juga sangat berpengaruh. Jangan lupa untuk melakukan pemeriksaan kadar hemoglobin secara berkala untuk memantau kondisi tubuh.',
                'url' => '/storage/posters/Cegah-Anemia.png',
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Jenis-Jenis Anemia',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Penjelasan berbagai jenis anemia dan penyebabnya yang perlu dikenali sejak dini.',
                'content' => 'Anemia memiliki berbagai jenis dengan penyebab yang berbeda-beda. Anemia defisiensi zat besi adalah yang paling umum, terutama pada remaja putri, dengan gejala lemas, pucat, dan kurang fokus. Anemia defisiensi vitamin C terjadi karena kekurangan vitamin C yang membantu penyerapan zat besi. Anemia makrositik disebabkan kekurangan vitamin B12 atau asam folat dengan gejala kesemutan dan gangguan memori. Anemia hemolitik terjadi saat sel darah merah hancur lebih cepat dari normal. Anemia sel sabit adalah kelainan genetik yang menyebabkan sel darah berbentuk sabit. Anemia aplastik adalah jenis paling serius yang dapat disebabkan oleh bahan kimia, obat, virus, atau autoimun.',
                'url' => '/storage/posters/Jenis-jenis-Anemia.png',
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Klasifikasi Anemia',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Informasi klasifikasi anemia berdasarkan kadar hemoglobin dan tingkat keparahan.',
                'content' => 'Anemia diklasifikasikan berdasarkan kadar hemoglobin (Hb) dalam darah. Anemia ringan memiliki kadar Hb 11-11,9 g/dl dengan gejala lelah ringan, lesu, dan kurang bertenaga namun sering tidak disadari. Anemia sedang memiliki kadar Hb 8-10,9 g/dl dengan gejala wajah pucat, mudah lelah, dan pusing yang sudah mengganggu aktivitas sehari-hari. Anemia berat memiliki kadar Hb kurang dari 8 g/dl dengan gejala sesak napas, jantung berdebar, dan lemah ekstrem yang harus segera ditangani untuk mencegah komplikasi serius. Pemeriksaan kadar Hb secara rutin dan konsultasi dengan tenaga kesehatan sangat penting untuk pencegahan dan penanganan yang tepat.',
                'url' => '/storage/posters/Klasifikasi-Anemia.png',
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pencegahan dan Penanggunlangan Anemia',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Strategi efektif mencegah dan menangani anemia pada remaja dan wanita usia subur.',
                'content' => 'Anemia dapat dicegah dan ditanggulangi dengan memenuhi kebutuhan zat besi tubuh untuk pembentukan hemoglobin optimal. Langkah-langkah pencegahan meliputi konsumsi makanan kaya zat besi dengan vitamin C untuk meningkatkan penyerapan, hindari konsumsi penghambat zat besi seperti teh, kopi, dan makanan tinggi kalsium saat makan utama. Suplementasi Tablet Tambah Darah (TTD) sangat dianjurkan saat asupan zat besi dari makanan belum cukup, dengan manfaat meningkatkan kadar Hb, membantu cadangan zat besi, dan mencegah anemia berulang. Konsumsi produk yang difortifikasi zat besi juga membantu menambah asupan zat besi ke dalam bahan pangan. Remaja dan wanita usia subur adalah generasi masa depan yang kuat, sehingga pencegahan anemia sejak dini dengan makanan bergizi, konsumsi TTD, dan pilihan makanan cerdas sangat penting.',
                'url' => '/storage/posters/Pencegahan-dan-Penanggulangan-Anemia.png',
                'order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mengapa Remaja Putri Rentan Anemia',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Faktor biologis dan pola hidup yang membuat remaja putri rentan terhadap anemia.',
                'content' => 'Remaja putri dan wanita usia subur termasuk kelompok paling rentan terkena anemia karena tubuh mereka membutuhkan lebih banyak zat besi. Faktor utama penyebabnya adalah pertumbuhan pesat saat pubertas yang menyebabkan kehilangan darah dan kebutuhan zat besi dua kali lebih banyak saat haid. Kehilangan darah saat menstruasi juga menyebabkan kehilangan zat besi dua kali lebih banyak saat haid. Diet yang salah dengan mengurangi asupan protein hewani seperti daging, telur, dan ikan yang penting untuk pembentukan hemoglobin turut berkontribusi pada risiko anemia. Oleh karena itu, penting untuk menjaga asupan zat besi melalui makanan bergizi, pemeriksaan Hb secara rutin, dan edukasi diri sejak dini karena remaja sehat adalah generasi hebat.',
                'url' => '/storage/posters/Rentan-Anemia.png',
                'order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kenali Penyebab Anemia pada Remaja',
                'type' => 'poster',
                'section' => 'Poster',
                'description' => 'Faktor penyebab utama anemia pada remaja dan pentingnya edukasi serta pencegahan menyeluruh.',
                'content' => 'Penyebab utama anemia pada remaja adalah kekurangan zat besi yang dipicu oleh berbagai faktor. Asupan makanan tidak seimbang dengan pola makan rendah zat besi, vitamin C, asam folat, dan protein serta tidak sesuai kebutuhan gizi remaja dapat menyebabkan tubuh kekurangan bahan baku untuk membentuk sel darah merah. Kurangnya pengetahuan gizi menyebabkan remaja tidak sadar pentingnya konsumsi makanan bergizi seimbang. Kondisi sosial ekonomi rendah membatasi akses terhadap makanan sehat, suplemen, dan layanan kesehatan yang dapat memperbesar risiko anemia. Pendidikan dan kesadaran kurang membuat remaja cenderung mengabaikan gejala awal dan memilih makanan tanpa mempertimbangkan nilai gizinya. Menstruasi berlebihan meningkatkan risiko kekurangan zat besi, sementara penyakit infeksi seperti cacingan, TBC, dan malaria dapat memperparah kondisi anemia. Makanan penghambat zat besi seperti teh, kopi, dan makanan tinggi kalsium yang dikonsumsi berlebihan dapat menghambat penyerapan zat besi. Anemia bukan sekadar rasa lelah biasa, tetapi kondisi serius yang dapat mengganggu aktivitas dan prestasi remaja.',
                'url' => '/storage/posters/Penyebab-Anemia.png',

                'order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fakta Seputar Talasemia',
                'type' => 'video',
                'section' => 'Video',
                'description' => 'Video edukasi yang menjelaskan apa itu talasemia, Jenis-Jenis Talasemia, serta Pencegahan Talasemia.',
                'content' => 'Video ini memberikan informasi dasar mengenai talasemia, Jenis-Jenis dari Talasemia. Dijelaskan penyebab, gejala umum, serta pentingnya deteksi dini dan pencegahan untuk Talasemia. Video ini bertujuan untuk meningkatkan kesadaran masyarakat tentang talasemia.',
                'url' => 'https://www.youtube.com/embed/ARc44SDSIsY?si=2GIMVYj4g2qaOyTy',
                'order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Apa yang Kamu Ketahui Tentang Anemia?',
                'type' => 'video',
                'section' => 'Video',
                'description' => 'Tablet tambah darah memiliki peran yang sangat penting untuk mencegah anemia terutama bagi para remaja putri, namun remaja putra juga boleh mengonsumsi tablet tambah darah.',
                'content' => 'Video ini menyajikan pertanyaan interaktif untuk menguji pengetahuan remaja tentang anemia. Disampaikan informasi dasar mengenai anemia, mengapa penting untuk mengetahuinya, dan bagaimana kondisi ini dapat memengaruhi aktivitas sehari-hari. Video ini bertujuan untuk memicu kesadaran dan minat remaja terhadap kesehatan darah mereka.',
                'url' => 'https://www.youtube.com/embed/qeSNW_uT7cQ?si=TtQkoIYYp5Me7aem',
                'order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ILM Tablet Tambah Darah (TTD) Anemia',
                'type' => 'video',
                'section' => 'Video',
                'description' => 'Iklan Layanan Masyarakat dari Kementerian Kesehatan RI tentang pentingnya konsumsi Tablet Tambah Darah untuk mencegah anemia, terutama pada remaja putri.',
                'content' => 'Video ILM ini menggambarkan situasi umum remaja yang mengalami gejala anemia seperti lesu dan sulit konsentrasi. Disampaikan pesan penting tentang manfaat mengonsumsi Tablet Tambah Darah (TTD) secara rutin sebagai upaya pencegahan dan penanganan anemia. Video ini menekankan pentingnya menjaga kesehatan darah untuk aktivitas yang optimal.',
                'url' => 'https://www.youtube.com/embed/_xWFpVmK_TU?si=Prvo7ja6EILZE5WJ',
                'order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tetap Segar Sepanjang Hari',
                'type' => 'video',
                'section' => 'Video',
                'description' => 'Video ajakan dari Dion Wiyoko untuk menjaga kesegaran dan kebersihan tubuh sepanjang hari.',
                'content' => 'Video singkat ini menampilkan Dion Wiyoko yang mengajak penonton untuk tetap aktif dan menjaga kesegaran tubuh, terutama setelah beraktivitas. Meskipun bukan video edukasi kesehatan spesifik, ini bisa dikaitkan dengan gaya hidup aktif yang mendukung kesehatan secara umum. Kampanye #StayCool24/7 menekankan pentingnya kebersihan diri untuk kenyamanan dan kepercayaan diri.',
                'url' => 'https://www.youtube.com/embed/-vQDKE4QsHM?si=s89vLXNJUVQa7ZIx',
                'order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Manfaat Tablet Tambah Darah',
                'type' => 'video',
                'section' => 'Video',
                'description' => 'Video edukasi animasi yang menjelaskan secara detail tentang Tablet Tambah Darah (TTD), manfaatnya, dan cara konsumsi yang benar untuk mencegah anemia.',
                'content' => 'Video animasi ini memberikan penjelasan komprehensif tentang Tablet Tambah Darah (TTD). Dibahas mengapa TTD penting, terutama bagi remaja putri, bagaimana TTD bekerja dalam tubuh untuk mencegah anemia, serta panduan praktis mengenai dosis dan waktu konsumsi yang tepat. Video ini juga menyoroti pentingnya kepatuhan dalam mengonsumsi TTD untuk mencapai hasil kesehatan yang optimal.',
                'url' => 'https://www.youtube.com/embed/CRCJ5ibZSiw?si=xjtDGqIG29cnirU4',
                'order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
